### ISSUE TITLE
Fix: internal polishing

### ISSUE THREAD

**Issue by tipogi** [pubky/pubky-nexus#50]
As we develop our project, we've identified some internal improvements that need our attention alongside new feature development. These aren't visible to end-users but are crucial for the project's long-term success:

- [ ] Split up the tests inside their respective model files, instead of having a single file to define all integration tests (`/tests`)
- [x] Create an environment file for database benchmarks. This will allow us to make different queries instead of having them hard-coded (`/benches`)
- [x] Map graph database `Row` data type to Rust `struct`s. This converts the raw row data into a strongly-typed Rust structure
- [x] For new structs that should have default values, implement the `Default` trait instead of manually defining default values
- [x] Implement unique constraints and indexes in the graph database schema to enforce data integrity and prevent duplicate entries
- [x] Implement event validation pipeline: verify data integrity and format and transform data (e.g., string to `pubkey_user_id`, string to `Crockfordbase32` encoding). Filter valid events before processing to ensure consistent and properly formatted data
- [ ] ...

**Comment by SHAcollision** [comment]
@tipogi some of these items are already completed. Maybe almost all of them are completed or partially done. If anything left, we should create an issue for it and close here. What do you think?

**Comment by SHAcollision** [comment]
Closing, opened https://github.com/pubky/pubky-nexus/issues/202
